name: get_b_cdn

#0 5-15 * * * 每天5-15点整点触发
#0 */8 * * * 每隔8小时触发
#10 0 * * * 每天0点10分触发
on:
  schedule:
    - cron: '10 16 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install requests selenium zhconv PyExecJS

      - name: Run script
        run: python ${{ github.workspace }}/run.py

      - name: commit-cdn-txt
        run: |
          git config --local user.email "f0rum@qq.com"
          git config --local user.name "happymem2023"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          git push -f
